version: "3.7"

services:
  # default:

  #___________[API Container Service]_______________________
  helloworld-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOST=localhost
      - DB_PORT=3366
      - DB_DATABASE=mydb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    container_name: helloworld-api
    depends_on:
      - db
    ports:
      - "8090:80" # local System port : Port on container or App running Port

  #___________[Web_App Container Service]___________________
  helloworld-app:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        BUILD_CMD: build
    container_name: helloworld-app
    ports:
      - "8080:80" # local System port : Port on container

  #___________[MySQL Service]_______________________
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3366:3306"
